"""create weapons table

Revision ID: 51833416da5e
Revises: b11939f28b72
Create Date: 2025-12-03 06:03:55.554620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51833416da5e'
down_revision: Union[str, None] = 'b11939f28b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weapons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('workbench', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('ammo_type', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('flavor_text', sa.String(), nullable=True),
    sa.Column('stat_block', sa.JSON(), nullable=False),
    sa.Column('loadout_slots', sa.JSON(), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metaforge_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metaforge_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weapons_ammo_type'), 'weapons', ['ammo_type'], unique=False)
    op.create_index(op.f('ix_weapons_id'), 'weapons', ['id'], unique=False)
    op.create_index(op.f('ix_weapons_name'), 'weapons', ['name'], unique=False)
    op.create_index(op.f('ix_weapons_rarity'), 'weapons', ['rarity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weapons_rarity'), table_name='weapons')
    op.drop_index(op.f('ix_weapons_name'), table_name='weapons')
    op.drop_index(op.f('ix_weapons_id'), table_name='weapons')
    op.drop_index(op.f('ix_weapons_ammo_type'), table_name='weapons')
    op.drop_table('weapons')
    # ### end Alembic commands ###
