"""create loadouts table

Revision ID: a40998aa9111
Revises: 3061704f9dd1
Create Date: 2025-12-12 04:30:41.617431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a40998aa9111'
down_revision: Union[str, None] = '3061704f9dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('workbench', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('ammo_type', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('flavor_text', sa.String(), nullable=True),
    sa.Column('stat_block', sa.JSON(), nullable=False),
    sa.Column('loadout_slots', sa.JSON(), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metaforge_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metaforge_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_ammo_type'), 'items', ['ammo_type'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_item_type'), 'items', ['item_type'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_index(op.f('ix_items_rarity'), 'items', ['rarity'], unique=False)
    op.create_table('loadouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('downvotes', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loadouts_id'), 'loadouts', ['id'], unique=False)
    op.create_index(op.f('ix_loadouts_name'), 'loadouts', ['name'], unique=False)
    op.create_table('loadout_items',
    sa.Column('loadout_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loadout_id'], ['loadouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('loadout_id', 'item_id')
    )
    op.drop_index('ix_weapons_ammo_type', table_name='weapons')
    op.drop_index('ix_weapons_id', table_name='weapons')
    op.drop_index('ix_weapons_name', table_name='weapons')
    op.drop_index('ix_weapons_rarity', table_name='weapons')
    op.drop_table('weapons')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weapons',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('item_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rarity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('workbench', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subcategory', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ammo_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('flavor_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stat_block', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('loadout_slots', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('locations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('metaforge_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('metaforge_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='weapons_pkey')
    )
    op.create_index('ix_weapons_rarity', 'weapons', ['rarity'], unique=False)
    op.create_index('ix_weapons_name', 'weapons', ['name'], unique=False)
    op.create_index('ix_weapons_id', 'weapons', ['id'], unique=False)
    op.create_index('ix_weapons_ammo_type', 'weapons', ['ammo_type'], unique=False)
    op.drop_table('loadout_items')
    op.drop_index(op.f('ix_loadouts_name'), table_name='loadouts')
    op.drop_index(op.f('ix_loadouts_id'), table_name='loadouts')
    op.drop_table('loadouts')
    op.drop_index(op.f('ix_items_rarity'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_item_type'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_ammo_type'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
